### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by nikolaydubina** [nlpodyssey/goslide#3]
Hi guys, so did you finish port? What's the status?

**Comment by marco-nicola** [comment]
Hey there!

Alas, this project is still on hold, due to priorities on [spaGO](https://github.com/nlpodyssey/spago) and [other side-projects](https://github.com/SpecializedGeneralist/) which are absorbing most of our time.

A very rough translation from the original C++ code is actually rather complete... with quite a few caveats attached.

First, the port it's still up to the original project's status of ~1 year ago, but fortunately the amount of more recent changes on the original repo is quite minimal.

Our approach was to first coarsly translate the entire original codebase, and then proceed with testing and refactoring. The first translation step was mostly done, than we had to put the project on hold when we were just about to test it.

There are various different execution branches here and there, see for example the different `HashFunction` implementations. We only performed a couple of manual tests just with the [default configuration](https://github.com/nlpodyssey/goslide/blob/master/configuration/configuration.go#L61) and, as far as I recall, we started getting reasonable results.

Anyway, there are many corners of the code which are completely untested. We must still test many different combinations of input data and configuration.  It's very likely that you would get weird results in certain cases, if not runtime errors.  And then, of course, we should also provide a set of automated test cases.

Despite the significant inactivity here, the project is not at all dead. We are finally reaching a stable API for our main project [spaGO](https://github.com/nlpodyssey/spago), as well as a decent coverage of supported models/algorithms, so we can soon move on to new topics. On our general roadmap, a significant subject is precisely the exploration of optimized techniques for CPU-only computation.

Due to the primitive status of the code, we didn't advertised this project too much yet. However, we still encourage contributions. A first way to contribute might be to review of the current port, by comparing the Go code with the original one and looking for mistakes. The Go code strictly follows the C++ code, so that a comparison should not be too difficult (sometimes almost line-by-line). Then, if you're not afraid of getting your hands dirty, please go on with fixing and testing. Issues and pull requests are welcome; even a little help would be much appreciated!
